### ISSUE TITLE
Add module that detects new MAC addresses on the network and fires an event

### ISSUE THREAD

**Issue by vlthr** [Homebrain/Homebrain#5]

**Comment by ErikBjare** [comment]
Can we close this @johan-bjareholt?

**Comment by johan-bjareholt** [comment]
Well, we still don't have MAC addresses, only hostnames and ip addresses.

I guess that having the mac address specifically shouldn't matter that much, in a sane local network every device should have a unique hostname that doesn't change, so i guess that we could close this.

**Comment by ErikBjare** [comment]
Yeah, I think MAC adresses would be unnecessary for now.

Closing.
